name: Build
permissions: read-all

on: [ push, workflow_dispatch ]

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        tf-version: [ 1.3.1, 1.3.2 ]
    steps:
      - name: Install terraform v${{ matrix.tf-version }}
        run: |
          curl -LO https://releases.hashicorp.com/terraform/${{ matrix.tf-version }}/terraform_${{ matrix.tf-version }}_linux_amd64.zip
          unzip terraform_${{ matrix.tf-version }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin
          rm *
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Validate examples terraform v${{ matrix.tf-version }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make examples
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - name: Run tests
        run: make test
  build:
    needs: [examples, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"
