name: Enable Auto merge PR
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  enable_automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2
        with:
          app-id: ${{ vars.AUTO_MERGE_APP_ID }}
          private-key: ${{ secrets.AUTO_MERGE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Enable auto-merge for PRs
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: '${{ steps.get_token.outputs.token }}'
